#+TITLE:8 Concatenating Two Arrays Using VLA Parameters
#+AUTHOR: Marcus Birkenkrahe (pledged)
#+SUBTITLE: CSC 240 (Data Structures) Lyon College Fall 2024
#+STARTUP:overview hideblocks indent
#+OPTIONS: toc:nil num:nil ^:nil
#+property: header-args:C :main yes :includes <stdio.h> :results output :exports both:
#+startup: overview hideblocks indent entitiespretty:
* Problem Statement

In this assignment, you will define a function to concatenate two
arrays =a= and =b= into a third array =c= using Variable-Length Array
(VLA) parameters. The sizes of =a= and =b= are determined at runtime,
and the function should copy both arrays successively into =c=.

* Tasks

1. Define a function =concat= that takes two arrays =a= and =b=, and a
   result array =c=.  The function should concatenate the two arrays
   into the third one.

   Function prototype:
   #+begin_src C
     void concat(int m, int n, int a[m], int b[n], int c[m+n]);
   #+end_src

2. Implement a simple example that concatenates two arrays =a = {1,2,3}=
   and =b = {4,5}=, calls the =concat= function, and prints the resulting
   concatenated array =c=.

3. Bonus: Create another version of the program that calls the function
   using compound literals.

* Expected Output

#+begin_example
  Array a: 1, 2, 3
  Array b: 4, 5
  Concatenated array c: 1 2 3 4 5
#+end_example

* Submission

1. *Meta data header* (title, author/pledge, subtitle, startup,
   property).
2. *Headlines* to structure your program (Problem, Implementation,
   Reflection).
3. *Code block(s)* with program header, function prototype and function
   documentation (purpose).
4. *Short reflection* about your experience and learning. 

