#+TITLE: Recursion (codealong I)
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: CSC 240 - Data structures with C++ - Lyon College, FA24
#+STARTUP:overview hideblocks indent
#+OPTIONS: toc:1 num:2 ^:nil
#+PROPERTY: header-args:C++ :main yes :includes <iostream> :results output :exports both :noweb yes
#+PROPERTY: header-args:C :main yes :includes <stdio.h> :results output :exports both :noweb yes
* Overview

- *Objectives:*
  + Compound literals to initialize arrays
  + Cast operators, lvalues and rvalues

* Variable-Length Array Parameters

- Variable-length arrays allow to state the length of an array in a
  function argument. They are most useful for multidimensional arrays.

- No direct link between =a= and =n=:
  #+begin_src C :results none
    int sum_array(int a[], int n) {
      // ...
    }
  #+end_src

- Create a "stack smashing error":
  #+begin_src C :results none

  #+end_src

- Using a variable-length array parameter, we can explicitly state that
  the length of ~a~ is ~n~:
  #+begin_src C :results none
    int sum_array(int n, int a[]) {
      // ...
    }
  #+end_src

- But now the order of parameters is important: ~int n, int a[n]~ is OK,
  but ~int a[n], int n~ is illegal.

- *Practice:* Sum an array of length 10 without VLA (=sum_array=), and
  with VLA (=sum_array_vla=) then call the function with the values
  5,10,11 for n.
  #+begin_src C :main no :tangle vla.c
    int sum_array_vla(int n, int a[n]); // Variable-Length Array
    int sum_array(int a[], int n); // regular array

    int main(void)
    {
      int a[___]={______}; // another way of initializing arrays
      printf("vla: %d\n", sum_array_vla(___));
      printf("regular: %d ", sum_array(___));
      return 0;
    }

    int _____
    {
      int i, sum=0;
      for (i=0;i<n;i++)
        sum+=a[i];
      return sum;
    }

    int _____
    {
      int i, sum=0;
      for (i=0;i<n;i++)
        sum+=a[i];
      return sum;
    }
  #+end_src

- What did you find out?
  #+begin_quote

  #+end_quote

- Two-dimensional arrays are not limited to fixed column numbers:
  complete the block to generate this output
  #+begin_example
  : 0 1 2 3
  : 1 2 3 4
  : 2 3 4 5
  : 3 4 5 6
  : Sum: 48
  #+end_example

- Code:
  #+begin_src C :main no
    int _____

    int main(void)
    {
      int n = ___, m = ___, i, j;
      int a[n][m];

      for(i=0;i<n;i++) {
        for(j=0;j<m;j++) {
          a[i][j]=i+j;
          printf("%d ",a[i][j]);
        }
        printf("\n");
      }
      printf("Sum: %d\n", sum_two_dimensional_array(______));

      return 0;
    }

    int _____
    {
      int i,j,sum=0;
      for(i=0;i<n;i++)
        for(j=0;j<m;j++)
          sum+=a[i][j];
      return sum;
    }
  #+end_src


: 0 1 2 3
: 1 2 3 4
: 2 3 4 5
: 3 4 5 6
: Sum: 48

- Using keyboard input: Complete the =scanf= statement, then test the
  code for n = m = 4 using the shell code block below.
  #+begin_src C :main no :tangle vlaSum.c :results silent
    int sum_two_dimensional_array(int n, int m, int a[n][m]);

    int main(void)
    {
      int n, m, i, j; // n x m array, loop variables i, j
      int a[n][m];

      printf("Enter number of rows and columns: ");
      scanf(_____);

      for(i=0;i<n;i++) {
        for(j=0;j<m;j++) {
          a[i][j]=i+j;
          printf("%d ",a[i][j]);
        }
        printf("\n");
      }
      printf("Sum: %d\n", sum_two_dimensional_array(n, m, a));

      return 0;
    }

    int sum_two_dimensional_array(int n, int m, int a[n][m])
    {
      int i,j,sum=0;
      for(i=0;i<n;i++)
        for(j=0;j<m;j++)
          sum+=a[i][j];
      return sum;
    }
  #+end_src

- Testing:
  #+begin_src bash :results output
    gcc _____
    echo _____
  #+end_src

  #+RESULTS:

- Alternate ways to prototype VLA parameter functions:
  #+begin_src C :results none
    int func1( );
    int func2( );
    int func1( );
    int func1( );
  #+end_src

- VLA parameters can also be expressions to be evaluated:
  #+begin_src C :results none
    int concat(int m, int n, int a[m], int b[n], int c[m+n]);
  #+end_src

* Compound Literals

- The term 'literal' always refers to unchangeable language elements,
  and the term 'compound' means that keywords are combined, like in
  =i++=, the compound operator representing =i = i + 1=.

- Using a /compound literal/, declaring and initializing an array can be
  avoided altogether:
  #+name: sum_array2
  #+begin_src C :main no
    // prototype declaration - VLA parameter
    int sum_array2(___); 

    // main function
    int main()
    {
      printf("total = %d\n",
         sum_array2(___);
      return 0;
    }

    // function definition
    int sum_array2(int n, int a[n])
    {
      int i, sum = 0;
      for (i=0;i<n;i++)
        sum += a[i];
      return sum;
    }

  #+end_src

  #+RESULTS: sum_array2

- A compound literal resembles a cast =(int[])= applied to an
  initializer ={}=. It is also an /lvalue/, so the value of its elements
  can be changed. It can be made read-only by adding =const= before the
  type.

- An /lvalue/ (locator value) is an expression that points to a location
  in memory (that is it has an address):
  #+begin_src C :results none

  #+end_src

- An /rvalue/ (right-hand value) can only appear on the right of an
  assignment: It is a temporary value without a usable address.
  #+begin_src C :results none

  #+end_src
  
- A /cast/ is an operator that converts one type into another:
  #+begin_src C
    int i = 1;
    float x = 3.14;
    char c = 'a';
    char *ic = "22";

    printf("%f\n", ____(i)); // cast int to float (widening)
    printf("%d\n", ____(x)); // cast float to int (narrowing/truncates)
    printf("%c\n",c); // no cast
    printf("%d\n",____(c)); // cast char to int
    printf("%i\n", ____(ic)); // cast string (char pointer) to int
  #+end_src

  #+RESULTS:
  : 1.000000
  : 3
  : a
  : 97
  : 22

- =atoi= is a function from the C Standard Library (=stdlib.h=) that
  converts a numeric string into an integer value. 
  #+begin_example C
    int atoi(const char *str)
  #+end_example
  The argument is a constant pointer to a string. We'll learn more
  about strings later.

- Are functions and operators the same thing, for example the
  functions =stdlib::atoi=, =stdio::printf= vs. the operators =sizeof= and
  =(int)=?
  #+begin_quote

  #+end_quote

